title: Account Configuration
description: Configure Databricks Account
required: []
properties:
  metastore:
    title: Metastore Configuration
    type: object
    properties:
      storage:
        title: Storage Configuration
        type: object
        properties:
          enabled:
            title: Enable Storage
            type: boolean
            default: false

  cloud_resources:
    title: Cloud Resources Configuration
    type: object
    properties:
      credential:
        title: Credential Configuration
        type: object
        properties:
          policy:
            title: Credential Policy
            type: string
            enum: [managed, customer]
            default: customer
      storage:
        title: Storage Configuration
        type: array
        default:
          - name: main
            s3_prefix: thoughtworks
            s3_versioning: false
        items:
          type: object
          properties:
            name:
              title: Storage Name
              type: string
              default: main
            s3_prefix:
              title: S3 Prefix
              type: string
              default: thoughtworks
            s3_versioning:
              title: S3 Versioning
              type: boolean
              default: false
      # network:
      #   title: Network Configuration
      #   type: array
      #   default:
      #     - name: main
      #       cidr_block: "10.0.0.0/16"
      #       internet_gateway: true
      #       nat_gateway: true
      #       private_link: false
      #       vpc_flow_logs: false
      #   items:
      #     type: object
      #     properties:
      #       name:
      #         title: Network Name
      #         type: string
      #         default: main
      #       cidr_block:
      #         title: CIDR Block
      #         type: string
      #         default: "10.0.0.0/16"
      #       internet_gateway:
      #         title: Internet Gateway
      #         type: boolean
      #         default: true
      #       nat_gateway:
      #         title: NAT Gateway
      #         type: boolean
      #         default: true
      #       private_link:
      #         title: Private Link
      #         type: boolean
      #         default: false
      #       vpc_flow_logs:
      #         title: VPC Flow Logs
      #         type: boolean
      #         default: false
      encryption:
        title: Encryption Configuration
        type: array
        default:
          - name: main
            use_cases:
              - MANAGED_SERVICES
              - STORAGE
          - name: dbfs
            use_cases:
              - STORAGE
          - name: ms
            use_cases:
              - MANAGED_SERVICES
        items:
          type: object
          properties:
            name:
              title: Encryption Name
              type: string
            use_cases:
              title: Use Cases
              type: array
              items:
                type: string
                enum: [MANAGED_SERVICES, STORAGE]

  groups:
    title: Groups Configuration
    type: array
    default:
      - name: data_scientists
        entitlements:
          allow_cluster_create: true
      - name: developers
        entitlements:
          allow_cluster_create: false
      - name: dashboard
        entitlements:
          allow_cluster_create: false
    items:
      type: object
      properties:
        name:
          title: Group Name
          type: string
        entitlements:
          title: Group Entitlements
          type: object
          properties:
            allow_cluster_create:
              title: Allow Cluster Create
              type: boolean
              default: false

  config:
    title: Global Configuration
    type: object
    properties:
      number_of_azs:
        title: Number of AZs
        type: number
        default: 3
      single_nat_gateway:
        title: Single NAT Gateway
        type: boolean
        default: false
      enable_auto_prefix:
        title: Enable Auto Prefix
        type: boolean
        default: true
      enable_auto_suffix:
        title: Enable Auto Suffix
        type: boolean
        default: true
      create_groups:
        title: Create Groups
        type: boolean
        default: false
      network_acls:
        title: Network ACLs
        type: object
        properties:
          private:
            title: Private Network ACLs
            type: object
            properties:
              outbound:
                title: Outbound Rules
                type: array
                default:
                  - protocol: tcp
                    port: 80
                items:
                  type: object
                  properties:
                    protocol:
                      title: Protocol
                      type: string
                      enum: [tcp, udp, icmp]
                      default: tcp
                    port:
                      title: Port
                      type: number
                      default: 80

  tags:
    title: Global Tags
    type: object
    properties:
      databricks:
        title: Databricks Tag
        type: boolean
        default: true
      itoc_monitored:
        title: ITOC Monitored Tag
        type: boolean
        default: true
