title: Workspace Configuration
description: Configure Databricks Workspace
required: []
properties:
  workspaces:
    title: Workspaces Configuration
    type: array
    items:
      type: object
      properties:
        name:
          title: Workspace Name
          type: string
        storage:
          title: Storage Name
          type: string
        network:
          title: Network Name
          type: string
        encryption:
          title: Encryption Configuration
          type: object
          properties:
            storage:
              title: Storage Encryption
              type: string
        catalogs:
          title: Catalogs Configuration
          type: array
          items:
            type: object
            properties:
              name:
                title: Catalog Name
                type: string
              prefix:
                title: Enable Prefix
                type: boolean
              storage:
                title: Storage Configuration
                type: object
                properties:
                  s3_prefix:
                    title: S3 Prefix
                    type: string
              visible:
                title: Is Visible
                type: boolean
              isolated:
                title: Is Isolated
                type: boolean
              schemas:
                title: Schemas
                type: array
                items:
                  type: string
        external_locations:
          title: External Locations
          type: array
          items:
            type: object
            properties:
              name:
                title: Location Name
                type: string
              storage:
                title: Storage Configuration
                type: object
                properties:
                  create_bucket:
                    title: Create Bucket
                    type: boolean
                  s3_prefix:
                    title: S3 Prefix
                    type: string
        clusters:
          title: Clusters Configuration
          type: array
          items:
            type: object
            properties:
              name:
                title: Cluster Name
                type: string
              spark_version:
                title: Spark Version
                type: string
              photon:
                title: Enable Photon
                type: boolean
              driver_instance_type:
                title: Driver Instance Type
                type: string
              instance_type:
                title: Instance Type
                type: string
              spark_conf:
                title: Spark Configuration
                type: object
                additionalProperties:
                  type: string
              on_demand:
                title: On-Demand Configuration
                type: object
                properties:
                  composition:
                    title: Composition
                    type: string
                  bid_price_percentage:
                    title: Bid Price Percentage
                    type: number
              auto_terminate:
                title: Auto Terminate (minutes)
                type: number
        sql_warehouses:
          title: SQL Warehouses Configuration
          type: array
          items:
            type: object
            properties:
              name:
                title: Warehouse Name
                type: string
              size:
                title: Warehouse Size
                type: string
              photon:
                title: Enable Photon
                type: boolean
              serverless:
                title: Enable Serverless
                type: boolean
              min_clusters:
                title: Minimum Clusters
                type: number
              max_clusters:
                title: Maximum Clusters
                type: number
              spot_instance_policy:
                title: Spot Instance Policy
                type: string
              auto_terminate:
                title: Auto Terminate (minutes)
                type: number
        monitoring:
          title: Monitoring Configuration
          type: object
          properties:
            datadog:
              title: Enable Datadog
              type: boolean
            cloudwatch:
              title: Enable CloudWatch
              type: boolean
        acls:
          title: Access Control Lists
          type: object
          properties:
            compute_policy:
              title: Compute Policy ACLs
              type: array
              items:
                type: object
                properties:
                  name:
                    title: Policy Name
                    type: string
                  groups:
                    title: Group Permissions
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          title: Group Name
                          type: string
                        permission:
                          title: Permission
                          type: string
            compute:
              title: Compute ACLs
              type: array
              items:
                type: object
                properties:
                  name:
                    title: Cluster Name
                    type: string
                  groups:
                    title: Group Permissions
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          title: Group Name
                          type: string
                        permission:
                          title: Permission
                          type: string
            sql_warehouse:
              title: SQL Warehouse ACLs
              type: array
              items:
                type: object
                properties:
                  name:
                    title: Warehouse Name
                    type: string
                  groups:
                    title: Group Permissions
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          title: Group Name
                          type: string
                        permission:
                          title: Permission
                          type: string
            job:
              title: Job ACLs
              type: array
              items:
                type: object
                properties:
                  name:
                    title: Job Name
                    type: string
                  groups:
                    title: Group Permissions
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          title: Group Name
                          type: string
                        permission:
                          title: Permission
                          type: string
            delta_live_tables:
              title: Delta Live Tables ACLs
              type: array
              items:
                type: object
                properties:
                  name:
                    title: Table Name
                    type: string
                  groups:
                    title: Group Permissions
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          title: Group Name
                          type: string
                        permission:
                          title: Permission
                          type: string
            secret_scope:
              title: Secret Scope ACLs
              type: array
              items:
                type: object
                properties:
                  name:
                    title: Scope Name
                    type: string
                  groups:
                    title: Group Permissions
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          title: Group Name
                          type: string
                        permission:
                          title: Permission
                          type: string
            token:
              title: Token ACLs
              type: object
              properties:
                groups:
                  title: Group Permissions
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        title: Group Name
                        type: string
                      permission:
                        title: Permission
                        type: string
        uc_privileges:
          title: Unity Catalog Privileges
          type: object
          properties:
            metastore:
              title: Metastore Privileges
              type: object
              properties:
                groups:
                  title: Group Privileges
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        title: Group Name
                        type: string
                      privileges:
                        title: Privileges
                        type: array
                        items:
                          type: string
            catalog:
              title: Catalog Privileges
              type: array
              items:
                type: object
                properties:
                  catalog_name:
                    title: Catalog Name
                    type: string
                  groups:
                    title: Group Privileges
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          title: Group Name
                          type: string
                        privileges:
                          title: Privileges
                          type: array
                          items:
                            type: string
            schema:
              title: Schema Privileges
              type: array
              items:
                type: object
                properties:
                  catalog_name:
                    title: Catalog Name
                    type: string
                  schema_name:
                    title: Schema Name
                    type: string
                  groups:
                    title: Group Privileges
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          title: Group Name
                          type: string
                        privileges:
                          title: Privileges
                          type: array
                          items:
                            type: string
            table:
              title: Table Privileges
              type: array
              items:
                type: object
                properties:
                  catalog_name:
                    title: Catalog Name
                    type: string
                  schema_name:
                    title: Schema Name
                    type: string
                  table_name:
                    title: Table Name
                    type: string
                  groups:
                    title: Group Privileges
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          title: Group Name
                          type: string
                        privileges:
                          title: Privileges
                          type: array
                          items:
                            type: string
            view:
              title: View Privileges
              type: array
              items:
                type: object
                properties:
                  catalog_name:
                    title: Catalog Name
                    type: string
                  schema_name:
                    title: Schema Name
                    type: string
                  view_name:
                    title: View Name
                    type: string
                  groups:
                    title: Group Privileges
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          title: Group Name
                          type: string
                        privileges:
                          title: Privileges
                          type: array
                          items:
                            type: string
            volume:
              title: Volume Privileges
              type: array
              items:
                type: object
                properties:
                  catalog_name:
                    title: Catalog Name
                    type: string
                  schema_name:
                    title: Schema Name
                    type: string
                  volume_name:
                    title: Volume Name
                    type: string
                  groups:
                    title: Group Privileges
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          title: Group Name
                          type: string
                        privileges:
                          title: Privileges
                          type: array
                          items:
                            type: string
            external_location:
              title: External Location Privileges
              type: array
              items:
                type: object
                properties:
                  name:
                    title: Location Name
                    type: string
                  groups:
                    title: Group Privileges
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          title: Group Name
                          type: string
                        privileges:
                          title: Privileges
                          type: array
                          items:
                            type: string
        security_profile:
          title: Security Profile
          type: object
          properties:
            enabled:
              title: Enable Security Profile
              type: boolean
            compliance_standards:
              title: Compliance Standards
              type: array
              items:
                type: string
    default:
      - name: thoughtworks-main
        storage: main
        network: main
        encryption:
          storage: dbfs
        catalogs:
          - name: development
            storage:
              s3_prefix: thoughtworks
            visible: true
            isolated: false
            schemas:
              - bronze
              - silver
              - gold
        external_locations:
          - name: development
            storage:
              create_bucket: true
              s3_prefix: thoughtworks
        clusters:
          - name: Shared Cluster
            spark_version: LTS
            photon: false
            driver_instance_type: m4.large
            instance_type: m4.large
            spark_conf:
              spark.app.name: general_tasks
            on_demand:
              composition: DRIVER_ONLY
              bid_price_percentage: 100
            auto_terminate: 60
        sql_warehouses:
          - name: SQL Shared
            size: Small
            photon: true
            serverless: true
            min_clusters: 2
            max_clusters: 3
            spot_instance_policy: COST_OPTIMIZED
            auto_terminate: 60
        monitoring:
          datadog: false
          cloudwatch: false
        acls:
          compute_policy:
            - name: Power User Compute
              groups:
                - name: developers
                  permission: CAN_USE
          compute:
            - name: Shared Cluster
              groups:
                - name: developers
                  permission: CAN_RESTART
                - name: dashboard
                  permission: CAN_ATTACH_TO
          sql_warehouse:
            - name: SQL Shared
              groups:
                - name: developers
                  permission: CAN_USE
          job: []
          delta_live_tables: []
          secret_scope: []
          token:
            groups:
              - name: developers
                permission: CAN_USE
        uc_privileges:
          metastore:
            groups:
              - name: data_scientists
                privileges:
                  - CREATE_EXTERNAL_LOCATION
          catalog:
            - catalog_name: tw_demo
              groups:
                - name: data_scientists
                  privileges:
                    - ALL_PRIVILEGES
                - name: dashboard
                  privileges:
                    - USE_CATALOG
                    - SELECT
          schema:
            - catalog_name: tw_demo
              schema_name: bronze
              groups:
                - name: dashboard
                  privileges:
                    - ALL_PRIVILEGES
          table: []
          view: []
          volume: []
          external_location:
            - name: catalog-storage-tw-demo
              groups:
                - name: data_scientists
                  privileges:
                    - ALL_PRIVILEGES
                - name: developers
                  privileges:
                    - READ_FILES
                    - WRITE_FILES
        security_profile:
          enabled: false
          compliance_standards:
            - HIPAA
            - PCI-DSS